/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_monicacastillo;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Monica
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PopUpSuperheroes = new javax.swing.JPopupMenu();
        EliminarSuperheroe = new javax.swing.JMenuItem();
        ModificarSuperheroe = new javax.swing.JMenuItem();
        PopUpVillanos = new javax.swing.JPopupMenu();
        EliminarVillano = new javax.swing.JMenuItem();
        ModificarVillano = new javax.swing.JMenuItem();
        VentanaEscuadronSuperheroes = new javax.swing.JFrame();
        LideresSuperHeroe = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NombreEscuadron = new javax.swing.JTextField();
        BaseEscuadron = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaEscuadronSuperHeroes = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JtreeEscuadronSuperheroes = new javax.swing.JTree();
        jLabel18 = new javax.swing.JLabel();
        VentanaEscuadronVillanos = new javax.swing.JFrame();
        LideresVillanos = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaEscuadronVillanos = new javax.swing.JList<>();
        NombreEscuadronVillanos = new javax.swing.JTextField();
        BaseEscuadronVillanos = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        JtreeEscuadronVillanos = new javax.swing.JTree();
        jLabel25 = new javax.swing.JLabel();
        PopUpEscuadronSuperheroes = new javax.swing.JPopupMenu();
        EliminarEscuadronSuperHeroes = new javax.swing.JMenuItem();
        ModificarEscuadronSuperheroes = new javax.swing.JMenuItem();
        PopUpEscuadronVillanos = new javax.swing.JPopupMenu();
        EliminarEscuadronVillanos = new javax.swing.JMenuItem();
        ModificarEscuadronVillanos = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SuperHeroeRadio = new javax.swing.JRadioButton();
        VillanoRadio = new javax.swing.JRadioButton();
        NombreSuperHumano = new javax.swing.JTextField();
        PoderSuperHumano = new javax.swing.JTextField();
        DebilidadSuperHumano = new javax.swing.JTextField();
        FuerzaSuperHumano = new javax.swing.JFormattedTextField();
        AgilidadFisicaSuperHumano = new javax.swing.JFormattedTextField();
        AgilidadMetalSuperHumano = new javax.swing.JFormattedTextField();
        AgregarSuperHumano = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaSuperHeroes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaVillanos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        EscuadronSuperHeroes = new javax.swing.JButton();
        EscuadronVillanos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        EliminarSuperheroe.setText("Eliminar Super Heroe");
        EliminarSuperheroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarSuperheroeActionPerformed(evt);
            }
        });
        PopUpSuperheroes.add(EliminarSuperheroe);

        ModificarSuperheroe.setText("Modificar Super Heroe");
        ModificarSuperheroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarSuperheroeActionPerformed(evt);
            }
        });
        PopUpSuperheroes.add(ModificarSuperheroe);

        EliminarVillano.setText("Eliminar Villano");
        EliminarVillano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVillanoActionPerformed(evt);
            }
        });
        PopUpVillanos.add(EliminarVillano);

        ModificarVillano.setText("Modificar Villano");
        ModificarVillano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarVillanoActionPerformed(evt);
            }
        });
        PopUpVillanos.add(ModificarVillano);

        jLabel12.setText("Agregar Escuadron");

        jLabel13.setText("Nombre");

        jLabel14.setText("Lugar de su base");

        jLabel15.setText("Lider");

        jLabel16.setText("Lista Miembros");

        ListaEscuadronSuperHeroes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaEscuadronSuperHeroesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ListaEscuadronSuperHeroes);

        jLabel17.setText("Lista Escuadrones");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        JtreeEscuadronSuperheroes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(JtreeEscuadronSuperheroes);

        jLabel18.setText("Jtree Escuadrones");

        javax.swing.GroupLayout VentanaEscuadronSuperheroesLayout = new javax.swing.GroupLayout(VentanaEscuadronSuperheroes.getContentPane());
        VentanaEscuadronSuperheroes.getContentPane().setLayout(VentanaEscuadronSuperheroesLayout);
        VentanaEscuadronSuperheroesLayout.setHorizontalGroup(
            VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(150, 150, 150))
            .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(30, 30, 30)
                .addGroup(VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(158, 158, 158))
                    .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                        .addGroup(VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BaseEscuadron, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreEscuadron, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LideresSuperHeroe, 0, 215, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                        .addGap(35, 35, 35))))
        );
        VentanaEscuadronSuperheroesLayout.setVerticalGroup(
            VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addGap(21, 21, 21)
                .addGroup(VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                        .addGroup(VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel14))
                            .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                                .addComponent(NombreEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(BaseEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(LideresSuperHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel16))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel19.setText("Agregar Escuadron");

        jLabel20.setText("Nombre");

        jLabel21.setText("Lugar de su base");

        jLabel22.setText("Lider");

        jLabel23.setText("Lista Miembros");

        jLabel24.setText("Lista Escuadrones");

        ListaEscuadronVillanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaEscuadronVillanosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ListaEscuadronVillanos);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        JtreeEscuadronVillanos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane6.setViewportView(JtreeEscuadronVillanos);

        jLabel25.setText("Jtree Escuadrones");

        javax.swing.GroupLayout VentanaEscuadronVillanosLayout = new javax.swing.GroupLayout(VentanaEscuadronVillanos.getContentPane());
        VentanaEscuadronVillanos.getContentPane().setLayout(VentanaEscuadronVillanosLayout);
        VentanaEscuadronVillanosLayout.setHorizontalGroup(
            VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaEscuadronVillanosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(23, 23, 23)
                .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaEscuadronVillanosLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaEscuadronVillanosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BaseEscuadronVillanos)
                            .addComponent(NombreEscuadronVillanos)
                            .addComponent(LideresVillanos, 0, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaEscuadronVillanosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(141, 141, 141))
        );
        VentanaEscuadronVillanosLayout.setVerticalGroup(
            VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaEscuadronVillanosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24))
                .addGap(28, 28, 28)
                .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaEscuadronVillanosLayout.createSequentialGroup()
                        .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(NombreEscuadronVillanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(BaseEscuadronVillanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(LideresVillanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel23))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        EliminarEscuadronSuperHeroes.setText("Eliminar Escuadron");
        EliminarEscuadronSuperHeroes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEscuadronSuperHeroesActionPerformed(evt);
            }
        });
        PopUpEscuadronSuperheroes.add(EliminarEscuadronSuperHeroes);

        ModificarEscuadronSuperheroes.setText("ModificarEscuadron");
        ModificarEscuadronSuperheroes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEscuadronSuperheroesActionPerformed(evt);
            }
        });
        PopUpEscuadronSuperheroes.add(ModificarEscuadronSuperheroes);

        EliminarEscuadronVillanos.setText("Eliminar Escuadron");
        EliminarEscuadronVillanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEscuadronVillanosActionPerformed(evt);
            }
        });
        PopUpEscuadronVillanos.add(EliminarEscuadronVillanos);

        ModificarEscuadronVillanos.setText("Modificar Escuadron");
        ModificarEscuadronVillanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEscuadronVillanosActionPerformed(evt);
            }
        });
        PopUpEscuadronVillanos.add(ModificarEscuadronVillanos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agregar SuperHumano");

        jLabel2.setText("¿Heroe o Supervillano?");

        jLabel3.setText("Nombre");

        jLabel4.setText("Poder");

        jLabel5.setText("Debilidad");

        jLabel7.setText("Fuerza");

        jLabel8.setText("Agilidad Fisica");

        jLabel9.setText("Agilidad Mental");

        buttonGroup1.add(SuperHeroeRadio);
        SuperHeroeRadio.setText("Super Heroe");

        buttonGroup1.add(VillanoRadio);
        VillanoRadio.setText("Villano");

        FuerzaSuperHumano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        AgilidadFisicaSuperHumano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        AgilidadMetalSuperHumano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        AgregarSuperHumano.setText("Agregar SuperHumano");
        AgregarSuperHumano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarSuperHumanoMouseClicked(evt);
            }
        });

        jLabel10.setText("Listar SuperHeroes");

        jLabel11.setText("Listar Villanos");

        ListaSuperHeroes.setModel(new DefaultListModel());
        ListaSuperHeroes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaSuperHeroesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaSuperHeroes);

        ListaVillanos.setModel(new DefaultListModel());
        ListaVillanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaVillanosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListaVillanos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(171, 171, 171))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SuperHeroeRadio)
                                .addGap(18, 18, 18)
                                .addComponent(VillanoRadio))
                            .addComponent(NombreSuperHumano)
                            .addComponent(PoderSuperHumano)
                            .addComponent(DebilidadSuperHumano)
                            .addComponent(FuerzaSuperHumano)
                            .addComponent(AgilidadFisicaSuperHumano)
                            .addComponent(AgilidadMetalSuperHumano)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(AgregarSuperHumano)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(179, 179, 179))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SuperHeroeRadio)
                            .addComponent(VillanoRadio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NombreSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PoderSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DebilidadSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(FuerzaSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(AgilidadFisicaSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(AgilidadMetalSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(AgregarSuperHumano))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar SuperHumano", jPanel1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("¿Que tipo de escuadron desea agregar?");

        EscuadronSuperHeroes.setText("Escuadron de Superheroes");
        EscuadronSuperHeroes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscuadronSuperHeroesMouseClicked(evt);
            }
        });

        EscuadronVillanos.setText("Escuadron de Villanos");
        EscuadronVillanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscuadronVillanosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(EscuadronSuperHeroes, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(EscuadronVillanos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscuadronSuperHeroes, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EscuadronVillanos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Escuadron", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarSuperHumanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarSuperHumanoMouseClicked
        // TODO add your handling code here:
        try {
            String nombre, poder, debilidad;
            Escuadron escuadron = null;
            double fuerza, amental, afisica;
            nombre = NombreSuperHumano.getText();
            poder = PoderSuperHumano.getText();
            debilidad = DebilidadSuperHumano.getText();
            fuerza = Double.parseDouble(FuerzaSuperHumano.getText());
            afisica = Double.parseDouble(AgilidadFisicaSuperHumano.getText());
            amental = Double.parseDouble(AgilidadMetalSuperHumano.getText());
            if (ValidacionNombreExistente(nombre) == false) {
                nombres.add(nombre);
                if ((ValidacionNumeros(amental, afisica, fuerza) == true)) {
                    if (VillanoRadio.isSelected()) {
                        DefaultListModel modelo = (DefaultListModel) ListaVillanos.getModel();
                        modelo.addElement(new Villano(nombre, poder, debilidad, escuadron, fuerza, afisica, amental));
                        ListaVillanos.setModel(modelo);
                        DefaultComboBoxModel villanolider = (DefaultComboBoxModel) LideresVillanos.getModel();
                        villanolider.addElement(new Villano(nombre, poder, debilidad, escuadron, fuerza, afisica, amental));
                        ListaVillanos.setModel(villanolider);
                    } else {
                        DefaultComboBoxModel heroelider = (DefaultComboBoxModel) LideresSuperHeroe.getModel();
                        heroelider.addElement(new Villano(nombre, poder, debilidad, escuadron, fuerza, afisica, amental));
                        ListaSuperHeroes.setModel(heroelider);
                        DefaultListModel modelo2 = (DefaultListModel) ListaSuperHeroes.getModel();
                        modelo2.addElement(new Villano(nombre, poder, debilidad, escuadron, fuerza, afisica, amental));
                        ListaSuperHeroes.setModel(modelo2);
                    } // Fin If
                } else {
                    JOptionPane.showMessageDialog(this, "¡No cuenta con las habilidades necesarias para ser Heroe o Villano!");
                } // Fin Else
                NombreSuperHumano.setText("");
                PoderSuperHumano.setText("");
                DebilidadSuperHumano.setText("");
                FuerzaSuperHumano.setText("");
                AgilidadFisicaSuperHumano.setText("");
                AgilidadMetalSuperHumano.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "¡El nombre ya existe, porfavor eliga otro!");
                NombreSuperHumano.setText("");
                PoderSuperHumano.setText("");
                DebilidadSuperHumano.setText("");
                FuerzaSuperHumano.setText("");
                AgilidadFisicaSuperHumano.setText("");
                AgilidadMetalSuperHumano.setText("");
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_AgregarSuperHumanoMouseClicked

    private void ListaSuperHeroesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaSuperHeroesMouseClicked
        // TODO add your handling code here:
        try {
            if (ListaSuperHeroes.getSelectedIndex() >= 0) {
                if (evt.isMetaDown()) {
                    PopUpSuperheroes.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ListaSuperHeroesMouseClicked

    private void ListaVillanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaVillanosMouseClicked
        // TODO add your handling code here:
        try {
            if (ListaVillanos.getSelectedIndex() >= 0) {
                if (evt.isMetaDown()) {
                    PopUpVillanos.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ListaVillanosMouseClicked

    private void EliminarSuperheroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSuperheroeActionPerformed
        // TODO add your handling code here:
        try {
            if (ListaSuperHeroes.getSelectedIndex() >= 0) {
                DefaultListModel modelo
                        = (DefaultListModel) ListaSuperHeroes.getModel();
                modelo.remove(ListaSuperHeroes.getSelectedIndex());
                ListaSuperHeroes.setModel(modelo);
                JOptionPane.showMessageDialog(this, "¡El Superheroe fue eliminado exitosamente!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_EliminarSuperheroeActionPerformed

    private void ModificarSuperheroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarSuperheroeActionPerformed
        // TODO add your handling code here:
        try {
            if (ListaSuperHeroes.getSelectedIndex() >= 0) {
                String nombre, poder, debilidad;
                double fuerza, amental, afisica;
                DefaultListModel modeloLISTA = (DefaultListModel) ListaSuperHeroes.getModel();
                nombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre: ");
                poder = JOptionPane.showInputDialog("Ingrese el nuevo poder: ");
                debilidad = JOptionPane.showInputDialog("Ingrese la nueva debilidad: ");
                fuerza = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva fuerza: "));
                afisica = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva agilidad fisica: "));
                amental = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva agilidad mental: "));
                if (ValidacionNombreExistente(nombre) == false) {
//                    nombres.remove(ListaSuperHeroes.getSelectedIndex());
//                    nombres.add(ListaSuperHeroes.getSelectedIndex(), nombre);
                    if ((ValidacionNumeros(amental, afisica, fuerza) == true)) {
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setNombre(nombre);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setPoder(poder);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setDebilidad(debilidad);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setFuerza(fuerza);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setAgilidadfisica(afisica);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setAgilidadmental(amental);
                        ListaSuperHeroes.setModel(modeloLISTA);
                    } else {
                        JOptionPane.showMessageDialog(this, "¡No cuenta con las habilidades necesarias para ser Heroe, por lo que no se realizaron las modificaciones!");
                    } // Fin Else
                } else {
                    JOptionPane.showMessageDialog(this, "¡El nombre ya existe, por lo que las modificaciones no se pudieron realizar!");
                } // Fin If
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_ModificarSuperheroeActionPerformed

    private void EliminarVillanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVillanoActionPerformed
        // TODO add your handling code here:
        if (ListaVillanos.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) ListaVillanos.getModel();
            modelo.remove(ListaVillanos.getSelectedIndex());
            ListaVillanos.setModel(modelo);
            JOptionPane.showMessageDialog(this, "¡El Villano fue eliminado exitosamente!");
        }
    }//GEN-LAST:event_EliminarVillanoActionPerformed

    private void ModificarVillanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarVillanoActionPerformed
        // TODO add your handling code here:
        try {
            if (ListaVillanos.getSelectedIndex() >= 0) {
                String nombre, poder, debilidad;
                double fuerza, amental, afisica;
                DefaultListModel modeloLISTA = (DefaultListModel) ListaVillanos.getModel();
                nombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre: ");
                poder = JOptionPane.showInputDialog("Ingrese el nuevo poder: ");
                debilidad = JOptionPane.showInputDialog("Ingrese la nueva debilidad: ");
                fuerza = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva fuerza: "));
                afisica = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva agilidad fisica: "));
                amental = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva agilidad mental: "));
                if (ValidacionNombreExistente(nombre) == false) {
//                    nombres.remove(ListaSuperHeroes.getSelectedIndex());
//                    nombres.add(ListaSuperHeroes.getSelectedIndex(), nombre);
                    if ((ValidacionNumeros(amental, afisica, fuerza) == true)) {
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setNombre(nombre);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setPoder(poder);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setDebilidad(debilidad);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setFuerza(fuerza);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setAgilidadfisica(afisica);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setAgilidadmental(amental);
                        ListaVillanos.setModel(modeloLISTA);
                    } else {
                        JOptionPane.showMessageDialog(this, "¡No cuenta con las habilidades necesarias para ser Villano, por lo que no se realizaron las modificaciones!");
                    } // Fin Else
                } else {
                    JOptionPane.showMessageDialog(this, "¡El nombre ya existe, por lo que las modificaciones no se pudieron realizar!");
                } // Fin If
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_ModificarVillanoActionPerformed

    private void EscuadronSuperHeroesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscuadronSuperHeroesMouseClicked
        // TODO add your handling code here:
        try {
            VentanaEscuadronSuperheroes.pack();
            VentanaEscuadronSuperheroes.setVisible(true);
            VentanaEscuadronSuperheroes.setLocationRelativeTo(null);
            this.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_EscuadronSuperHeroesMouseClicked

    private void EscuadronVillanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscuadronVillanosMouseClicked
        // TODO add your handling code here:
        try {
            VentanaEscuadronVillanos.pack();
            VentanaEscuadronVillanos.setVisible(true);
            VentanaEscuadronVillanos.setLocationRelativeTo(null);
            this.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_EscuadronVillanosMouseClicked

    private void EliminarEscuadronSuperHeroesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEscuadronSuperHeroesActionPerformed
        // TODO add your handling code here:
        if (ListaEscuadronSuperHeroes.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) ListaEscuadronSuperHeroes.getModel();
            modelo.remove(ListaEscuadronSuperHeroes.getSelectedIndex());
            ListaEscuadronSuperHeroes.setModel(modelo);
            JOptionPane.showMessageDialog(this, "¡El escuadron fue eliminado exitosamente!");
        }
        // Falta eliminar miembros del escuadron
    }//GEN-LAST:event_EliminarEscuadronSuperHeroesActionPerformed

    private void ModificarEscuadronSuperheroesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEscuadronSuperheroesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarEscuadronSuperheroesActionPerformed

    private void EliminarEscuadronVillanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEscuadronVillanosActionPerformed
        // TODO add your handling code here:
        if (ListaEscuadronVillanos.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) ListaEscuadronVillanos.getModel();
            modelo.remove(ListaEscuadronVillanos.getSelectedIndex());
            ListaEscuadronVillanos.setModel(modelo);
            JOptionPane.showMessageDialog(this, "¡El escuadron fue eliminado exitosamente!");
//            miembrosvillanos.get(ListaEscuadronVillanos.getSelectedIndex()).setEscuadron(null);
        }
    }//GEN-LAST:event_EliminarEscuadronVillanosActionPerformed

    private void ModificarEscuadronVillanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEscuadronVillanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarEscuadronVillanosActionPerformed

    private void ListaEscuadronSuperHeroesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaEscuadronSuperHeroesMouseClicked
        // TODO add your handling code here:
        try {
            if (ListaEscuadronSuperHeroes.getSelectedIndex() >= 0) {
                if (evt.isMetaDown()) {
                    PopUpEscuadronSuperheroes.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ListaEscuadronSuperHeroesMouseClicked

    private void ListaEscuadronVillanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaEscuadronVillanosMouseClicked
        // TODO add your handling code here:
        try {
            if (ListaEscuadronVillanos.getSelectedIndex() >= 0) {
                if (evt.isMetaDown()) {
                    PopUpEscuadronVillanos.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ListaEscuadronVillanosMouseClicked

    public boolean ValidacionNombreExistente(String nombre) {
        for (int i = 0; i < nombres.size(); i++) {
            if (nombres.get(i).equals(nombre)) {
                return true;
            } // Fin If
        } // Fin For
        return false;
    } // Fin Validacion Nombre Existente

    public boolean ValidacionNumeros(double amental, double afisica, double fuerza) {
        double suma;
        suma = amental + afisica + fuerza;
        if (suma == 100) {
            return true;
        } else {
            return false;
        } // Fin If
    } // Fin Validacion Numeros

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField AgilidadFisicaSuperHumano;
    private javax.swing.JFormattedTextField AgilidadMetalSuperHumano;
    private javax.swing.JButton AgregarSuperHumano;
    private javax.swing.JTextField BaseEscuadron;
    private javax.swing.JTextField BaseEscuadronVillanos;
    private javax.swing.JTextField DebilidadSuperHumano;
    private javax.swing.JMenuItem EliminarEscuadronSuperHeroes;
    private javax.swing.JMenuItem EliminarEscuadronVillanos;
    private javax.swing.JMenuItem EliminarSuperheroe;
    private javax.swing.JMenuItem EliminarVillano;
    private javax.swing.JButton EscuadronSuperHeroes;
    private javax.swing.JButton EscuadronVillanos;
    private javax.swing.JFormattedTextField FuerzaSuperHumano;
    private javax.swing.JTree JtreeEscuadronSuperheroes;
    private javax.swing.JTree JtreeEscuadronVillanos;
    private javax.swing.JComboBox<String> LideresSuperHeroe;
    private javax.swing.JComboBox<String> LideresVillanos;
    private javax.swing.JList<String> ListaEscuadronSuperHeroes;
    private javax.swing.JList<String> ListaEscuadronVillanos;
    private javax.swing.JList<String> ListaSuperHeroes;
    private javax.swing.JList<String> ListaVillanos;
    private javax.swing.JMenuItem ModificarEscuadronSuperheroes;
    private javax.swing.JMenuItem ModificarEscuadronVillanos;
    private javax.swing.JMenuItem ModificarSuperheroe;
    private javax.swing.JMenuItem ModificarVillano;
    private javax.swing.JTextField NombreEscuadron;
    private javax.swing.JTextField NombreEscuadronVillanos;
    private javax.swing.JTextField NombreSuperHumano;
    private javax.swing.JTextField PoderSuperHumano;
    private javax.swing.JPopupMenu PopUpEscuadronSuperheroes;
    private javax.swing.JPopupMenu PopUpEscuadronVillanos;
    private javax.swing.JPopupMenu PopUpSuperheroes;
    private javax.swing.JPopupMenu PopUpVillanos;
    private javax.swing.JRadioButton SuperHeroeRadio;
    private javax.swing.JFrame VentanaEscuadronSuperheroes;
    private javax.swing.JFrame VentanaEscuadronVillanos;
    private javax.swing.JRadioButton VillanoRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
private ArrayList<String> nombres = new ArrayList();
    private ArrayList<Villano> miembrosvillanos = new ArrayList();
    private ArrayList<Superheroe> miembrosheroes = new ArrayList();
}
