/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_monicacastillo;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Monica
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PopUpSuperheroes = new javax.swing.JPopupMenu();
        EliminarSuperheroe = new javax.swing.JMenuItem();
        ModificarSuperheroe = new javax.swing.JMenuItem();
        PopUpVillanos = new javax.swing.JPopupMenu();
        EliminarVillano = new javax.swing.JMenuItem();
        ModificarVillano = new javax.swing.JMenuItem();
        VentanaEscuadronSuperheroes = new javax.swing.JFrame();
        MiembrosSuperheroes = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        AgregarMiembroSuperheroe = new javax.swing.JButton();
        VentanaEscuadronVillanos = new javax.swing.JFrame();
        MiembrosVillanos = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        AgregarMiembroVillano = new javax.swing.JButton();
        PopUpEscuadron = new javax.swing.JPopupMenu();
        EliminarEscuadronSuperHeroes = new javax.swing.JMenuItem();
        ModificarEscuadronSuperheroes = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SuperHeroeRadio = new javax.swing.JRadioButton();
        VillanoRadio = new javax.swing.JRadioButton();
        NombreSuperHumano = new javax.swing.JTextField();
        PoderSuperHumano = new javax.swing.JTextField();
        DebilidadSuperHumano = new javax.swing.JTextField();
        FuerzaSuperHumano = new javax.swing.JFormattedTextField();
        AgilidadFisicaSuperHumano = new javax.swing.JFormattedTextField();
        AgilidadMetalSuperHumano = new javax.swing.JFormattedTextField();
        AgregarSuperHumano = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaSuperHeroes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaVillanos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nombreescuadron = new javax.swing.JTextField();
        baseescuadron = new javax.swing.JTextField();
        superheroeradioescua = new javax.swing.JRadioButton();
        villanoradioescua = new javax.swing.JRadioButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        ListaEscuadrones = new javax.swing.JList<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        JtreeEscuadrones = new javax.swing.JTree();
        AgregarEscuadrones = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        EliminarSuperheroe.setText("Eliminar Super Heroe");
        EliminarSuperheroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarSuperheroeActionPerformed(evt);
            }
        });
        PopUpSuperheroes.add(EliminarSuperheroe);

        ModificarSuperheroe.setText("Modificar Super Heroe");
        ModificarSuperheroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarSuperheroeActionPerformed(evt);
            }
        });
        PopUpSuperheroes.add(ModificarSuperheroe);

        EliminarVillano.setText("Eliminar Villano");
        EliminarVillano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVillanoActionPerformed(evt);
            }
        });
        PopUpVillanos.add(EliminarVillano);

        ModificarVillano.setText("Modificar Villano");
        ModificarVillano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarVillanoActionPerformed(evt);
            }
        });
        PopUpVillanos.add(ModificarVillano);

        jLabel29.setText("Seleccione un miembro");

        AgregarMiembroSuperheroe.setText("Agregar Miembro");
        AgregarMiembroSuperheroe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMiembroSuperheroeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VentanaEscuadronSuperheroesLayout = new javax.swing.GroupLayout(VentanaEscuadronSuperheroes.getContentPane());
        VentanaEscuadronSuperheroes.getContentPane().setLayout(VentanaEscuadronSuperheroesLayout);
        VentanaEscuadronSuperheroesLayout.setHorizontalGroup(
            VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                .addGroup(VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(MiembrosSuperheroes, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel29))
                    .addGroup(VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(AgregarMiembroSuperheroe)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        VentanaEscuadronSuperheroesLayout.setVerticalGroup(
            VentanaEscuadronSuperheroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaEscuadronSuperheroesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel29)
                .addGap(60, 60, 60)
                .addComponent(MiembrosSuperheroes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(AgregarMiembroSuperheroe)
                .addGap(20, 20, 20))
        );

        jLabel19.setText("Agregar Miembro");

        AgregarMiembroVillano.setText("Agregar Miembro");
        AgregarMiembroVillano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMiembroVillanoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VentanaEscuadronVillanosLayout = new javax.swing.GroupLayout(VentanaEscuadronVillanos.getContentPane());
        VentanaEscuadronVillanos.getContentPane().setLayout(VentanaEscuadronVillanosLayout);
        VentanaEscuadronVillanosLayout.setHorizontalGroup(
            VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaEscuadronVillanosLayout.createSequentialGroup()
                .addGroup(VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaEscuadronVillanosLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel19))
                    .addGroup(VentanaEscuadronVillanosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(AgregarMiembroVillano))
                    .addGroup(VentanaEscuadronVillanosLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(MiembrosVillanos, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        VentanaEscuadronVillanosLayout.setVerticalGroup(
            VentanaEscuadronVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaEscuadronVillanosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addGap(39, 39, 39)
                .addComponent(MiembrosVillanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(AgregarMiembroVillano)
                .addGap(40, 40, 40))
        );

        EliminarEscuadronSuperHeroes.setText("Eliminar Escuadron");
        EliminarEscuadronSuperHeroes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEscuadronSuperHeroesActionPerformed(evt);
            }
        });
        PopUpEscuadron.add(EliminarEscuadronSuperHeroes);

        ModificarEscuadronSuperheroes.setText("ModificarEscuadron");
        ModificarEscuadronSuperheroes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEscuadronSuperheroesActionPerformed(evt);
            }
        });
        PopUpEscuadron.add(ModificarEscuadronSuperheroes);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agregar SuperHumano");

        jLabel2.setText("¿Heroe o Supervillano?");

        jLabel3.setText("Nombre");

        jLabel4.setText("Poder");

        jLabel5.setText("Debilidad");

        jLabel7.setText("Fuerza");

        jLabel8.setText("Agilidad Fisica");

        jLabel9.setText("Agilidad Mental");

        buttonGroup1.add(SuperHeroeRadio);
        SuperHeroeRadio.setText("Super Heroe");

        buttonGroup1.add(VillanoRadio);
        VillanoRadio.setText("Villano");

        FuerzaSuperHumano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        AgilidadFisicaSuperHumano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        AgilidadMetalSuperHumano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        AgregarSuperHumano.setText("Agregar SuperHumano");
        AgregarSuperHumano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarSuperHumanoMouseClicked(evt);
            }
        });

        jLabel10.setText("Listar SuperHeroes");

        jLabel11.setText("Listar Villanos");

        ListaSuperHeroes.setModel(new DefaultListModel());
        ListaSuperHeroes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaSuperHeroesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaSuperHeroes);

        ListaVillanos.setModel(new DefaultListModel());
        ListaVillanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaVillanosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListaVillanos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(171, 171, 171))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SuperHeroeRadio)
                                .addGap(18, 18, 18)
                                .addComponent(VillanoRadio))
                            .addComponent(NombreSuperHumano)
                            .addComponent(PoderSuperHumano)
                            .addComponent(DebilidadSuperHumano)
                            .addComponent(FuerzaSuperHumano)
                            .addComponent(AgilidadFisicaSuperHumano)
                            .addComponent(AgilidadMetalSuperHumano)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(AgregarSuperHumano)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(179, 179, 179))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SuperHeroeRadio)
                            .addComponent(VillanoRadio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NombreSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PoderSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DebilidadSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(FuerzaSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(AgilidadFisicaSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(AgilidadMetalSuperHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(AgregarSuperHumano))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar SuperHumano", jPanel1);

        jLabel6.setText("Agregar Escuadron");

        jLabel15.setText("Nombre");

        jLabel22.setText("Lugar de la base");

        jLabel26.setText("Tipo de escuadron");

        buttonGroup2.add(superheroeradioescua);
        superheroeradioescua.setText("Superheroes");

        buttonGroup2.add(villanoradioescua);
        villanoradioescua.setText("Villanos");

        ListaEscuadrones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaEscuadronesMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(ListaEscuadrones);

        jLabel27.setText("Lista Escuadrones");

        jLabel28.setText("Jtree Escuadrones");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        JtreeEscuadrones.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane8.setViewportView(JtreeEscuadrones);

        AgregarEscuadrones.setText("Agregar Escuadrones");
        AgregarEscuadrones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarEscuadronesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(203, 203, 203))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(superheroeradioescua)
                                .addGap(10, 10, 10)
                                .addComponent(villanoradioescua))
                            .addComponent(baseescuadron)
                            .addComponent(nombreescuadron)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(AgregarEscuadrones)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(185, 185, 185))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel27))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(nombreescuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(baseescuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(superheroeradioescua)
                            .addComponent(villanoradioescua))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(AgregarEscuadrones)
                        .addContainerGap(171, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Agregar Escuadron", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarSuperHumanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarSuperHumanoMouseClicked
        // TODO add your handling code here:
        try {
            String nombre, poder, debilidad;
            Escuadron escuadron = null;
            double fuerza, amental, afisica;
            nombre = NombreSuperHumano.getText();
            poder = PoderSuperHumano.getText();
            debilidad = DebilidadSuperHumano.getText();
            fuerza = Double.parseDouble(FuerzaSuperHumano.getText());
            afisica = Double.parseDouble(AgilidadFisicaSuperHumano.getText());
            amental = Double.parseDouble(AgilidadMetalSuperHumano.getText());
            if (ValidacionNombreExistente(nombre) == false) {
                nombres.add(nombre);
                if ((ValidacionNumeros(amental, afisica, fuerza) == true)) {
                    if (VillanoRadio.isSelected()) {
                        DefaultListModel modelo = (DefaultListModel) ListaVillanos.getModel();
                        modelo.addElement(new Villano(nombre, poder, debilidad, escuadron, fuerza, afisica, amental));
                        ListaVillanos.setModel(modelo);
                        DefaultComboBoxModel villanolider = (DefaultComboBoxModel) MiembrosVillanos.getModel();
                        villanolider.addElement(new Villano(nombre, poder, debilidad, escuadron, fuerza, afisica, amental));
                        MiembrosVillanos.setModel(villanolider);
                    } else {
                        DefaultComboBoxModel heroelider = (DefaultComboBoxModel) MiembrosSuperheroes.getModel();
                        heroelider.addElement(new Villano(nombre, poder, debilidad, escuadron, fuerza, afisica, amental));
                        MiembrosSuperheroes.setModel(heroelider);
                        DefaultListModel modelo2 = (DefaultListModel) ListaSuperHeroes.getModel();
                        modelo2.addElement(new Villano(nombre, poder, debilidad, escuadron, fuerza, afisica, amental));
                        ListaSuperHeroes.setModel(modelo2);
                    } // Fin If
                } else {
                    JOptionPane.showMessageDialog(this, "¡No cuenta con las habilidades necesarias para ser Heroe o Villano!");
                } // Fin Else
                NombreSuperHumano.setText("");
                PoderSuperHumano.setText("");
                DebilidadSuperHumano.setText("");
                FuerzaSuperHumano.setText("");
                AgilidadFisicaSuperHumano.setText("");
                AgilidadMetalSuperHumano.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "¡El nombre ya existe, porfavor eliga otro!");
                NombreSuperHumano.setText("");
                PoderSuperHumano.setText("");
                DebilidadSuperHumano.setText("");
                FuerzaSuperHumano.setText("");
                AgilidadFisicaSuperHumano.setText("");
                AgilidadMetalSuperHumano.setText("");
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_AgregarSuperHumanoMouseClicked

    private void ListaSuperHeroesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaSuperHeroesMouseClicked
        // TODO add your handling code here:
        try {
            if (ListaSuperHeroes.getSelectedIndex() >= 0) {
                if (evt.isMetaDown()) {
                    PopUpSuperheroes.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ListaSuperHeroesMouseClicked

    private void ListaVillanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaVillanosMouseClicked
        // TODO add your handling code here:
        try {
            if (ListaVillanos.getSelectedIndex() >= 0) {
                if (evt.isMetaDown()) {
                    PopUpVillanos.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ListaVillanosMouseClicked

    private void EliminarSuperheroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSuperheroeActionPerformed
        // TODO add your handling code here:
        try {
            if (ListaSuperHeroes.getSelectedIndex() >= 0) {
                DefaultListModel modelo
                        = (DefaultListModel) ListaSuperHeroes.getModel();
                modelo.remove(ListaSuperHeroes.getSelectedIndex());
                ListaSuperHeroes.setModel(modelo);
                JOptionPane.showMessageDialog(this, "¡El Superheroe fue eliminado exitosamente!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_EliminarSuperheroeActionPerformed

    private void ModificarSuperheroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarSuperheroeActionPerformed
        // TODO add your handling code here:
        try {
            if (ListaSuperHeroes.getSelectedIndex() >= 0) {
                String nombre, poder, debilidad;
                double fuerza, amental, afisica;
                DefaultListModel modeloLISTA = (DefaultListModel) ListaSuperHeroes.getModel();
                nombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre: ");
                poder = JOptionPane.showInputDialog("Ingrese el nuevo poder: ");
                debilidad = JOptionPane.showInputDialog("Ingrese la nueva debilidad: ");
                fuerza = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva fuerza: "));
                afisica = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva agilidad fisica: "));
                amental = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva agilidad mental: "));
                if (ValidacionNombreExistente(nombre) == false) {
//                    nombres.remove(ListaSuperHeroes.getSelectedIndex());
//                    nombres.add(ListaSuperHeroes.getSelectedIndex(), nombre);
                    if ((ValidacionNumeros(amental, afisica, fuerza) == true)) {
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setNombre(nombre);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setPoder(poder);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setDebilidad(debilidad);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setFuerza(fuerza);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setAgilidadfisica(afisica);
                        ((Superheroe) modeloLISTA.get(ListaSuperHeroes.getSelectedIndex())).setAgilidadmental(amental);
                        ListaSuperHeroes.setModel(modeloLISTA);
                    } else {
                        JOptionPane.showMessageDialog(this, "¡No cuenta con las habilidades necesarias para ser Heroe, por lo que no se realizaron las modificaciones!");
                    } // Fin Else
                } else {
                    JOptionPane.showMessageDialog(this, "¡El nombre ya existe, por lo que las modificaciones no se pudieron realizar!");
                } // Fin If
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_ModificarSuperheroeActionPerformed

    private void EliminarVillanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVillanoActionPerformed
        // TODO add your handling code here:
        if (ListaVillanos.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) ListaVillanos.getModel();
            modelo.remove(ListaVillanos.getSelectedIndex());
            ListaVillanos.setModel(modelo);
            JOptionPane.showMessageDialog(this, "¡El Villano fue eliminado exitosamente!");
        }
    }//GEN-LAST:event_EliminarVillanoActionPerformed

    private void ModificarVillanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarVillanoActionPerformed
        // TODO add your handling code here:
        try {
            if (ListaVillanos.getSelectedIndex() >= 0) {
                String nombre, poder, debilidad;
                double fuerza, amental, afisica;
                DefaultListModel modeloLISTA = (DefaultListModel) ListaVillanos.getModel();
                nombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre: ");
                poder = JOptionPane.showInputDialog("Ingrese el nuevo poder: ");
                debilidad = JOptionPane.showInputDialog("Ingrese la nueva debilidad: ");
                fuerza = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva fuerza: "));
                afisica = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva agilidad fisica: "));
                amental = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva agilidad mental: "));
                if (ValidacionNombreExistente(nombre) == false) {
//                    nombres.remove(ListaSuperHeroes.getSelectedIndex());
//                    nombres.add(ListaSuperHeroes.getSelectedIndex(), nombre);
                    if ((ValidacionNumeros(amental, afisica, fuerza) == true)) {
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setNombre(nombre);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setPoder(poder);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setDebilidad(debilidad);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setFuerza(fuerza);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setAgilidadfisica(afisica);
                        ((Superheroe) modeloLISTA.get(ListaVillanos.getSelectedIndex())).setAgilidadmental(amental);
                        ListaVillanos.setModel(modeloLISTA);
                    } else {
                        JOptionPane.showMessageDialog(this, "¡No cuenta con las habilidades necesarias para ser Villano, por lo que no se realizaron las modificaciones!");
                    } // Fin Else
                } else {
                    JOptionPane.showMessageDialog(this, "¡El nombre ya existe, por lo que las modificaciones no se pudieron realizar!");
                } // Fin If
            } // Fin If
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        } // Fin Try Catch
    }//GEN-LAST:event_ModificarVillanoActionPerformed

    private void EliminarEscuadronSuperHeroesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEscuadronSuperHeroesActionPerformed
        // TODO add your handling code here:
//        if (ListaEscuadronSuperHeroes.getSelectedIndex() >= 0) {
//            DefaultListModel modelo
//                    = (DefaultListModel) ListaEscuadronSuperHeroes.getModel();
//            modelo.remove(ListaEscuadronSuperHeroes.getSelectedIndex());
//            ListaEscuadronSuperHeroes.setModel(modelo);
//            JOptionPane.showMessageDialog(this, "¡El escuadron fue eliminado exitosamente!");
//        }
        // Falta eliminar miembros del escuadron
    }//GEN-LAST:event_EliminarEscuadronSuperHeroesActionPerformed

    private void ModificarEscuadronSuperheroesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEscuadronSuperheroesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarEscuadronSuperheroesActionPerformed

    private void AgregarMiembroVillanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMiembroVillanoMouseClicked
        // TODO add your handling code here: 
        String nombre, base;
        SuperHumano lider;
        nombre = nombreescuadron.getText();
        base = baseescuadron.getText();
        lider = (SuperHumano) MiembrosVillanos.getSelectedItem();
        DefaultListModel modelo = (DefaultListModel) ListaEscuadrones.getModel();
        modelo.addElement(new Escuadron(nombre, base, "Villanos", lider));
        ListaEscuadrones.setModel(modelo);
        JOptionPane.showMessageDialog(this, "Se ha agregado el escuadron exitosamente");
        VentanaEscuadronVillanos.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_AgregarMiembroVillanoMouseClicked

    private void AgregarEscuadronesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarEscuadronesMouseClicked
        // TODO add your handling code here:
        if (superheroeradioescua.isSelected()) {
            VentanaEscuadronSuperheroes.pack();
            VentanaEscuadronSuperheroes.setVisible(true);
            VentanaEscuadronSuperheroes.setLocationRelativeTo(null);
            this.setVisible(false);
        } else {
            VentanaEscuadronVillanos.pack();
            VentanaEscuadronVillanos.setVisible(true);
            VentanaEscuadronVillanos.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_AgregarEscuadronesMouseClicked

    private void AgregarMiembroSuperheroeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMiembroSuperheroeMouseClicked
        // TODO add your handling code here:
        String nombre, base;
        SuperHumano lider;
        nombre = nombreescuadron.getText();
        base = baseescuadron.getText();
        lider = (SuperHumano) MiembrosSuperheroes.getSelectedItem();
        DefaultListModel modelo = (DefaultListModel) ListaEscuadrones.getModel();
        modelo.addElement(new Escuadron(nombre, base, "Heroes", lider));
        ListaEscuadrones.setModel(modelo);
        JOptionPane.showMessageDialog(this, "Se ha agregado el escuadron exitosamente");
        VentanaEscuadronSuperheroes.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_AgregarMiembroSuperheroeMouseClicked

    private void ListaEscuadronesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaEscuadronesMouseClicked
        // TODO add your handling code here:
        try {
            if (ListaEscuadrones.getSelectedIndex() >= 0) {
                if (evt.isMetaDown()) {
                    PopUpEscuadron.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ListaEscuadronesMouseClicked

    public boolean ValidacionNombreExistente(String nombre) {
        for (int i = 0; i < nombres.size(); i++) {
            if (nombres.get(i).equals(nombre)) {
                return true;
            } // Fin If
        } // Fin For
        return false;
    } // Fin Validacion Nombre Existente

    public boolean ValidacionNumeros(double amental, double afisica, double fuerza) {
        double suma;
        suma = amental + afisica + fuerza;
        if (suma == 100) {
            return true;
        } else {
            return false;
        } // Fin If
    } // Fin Validacion Numeros

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField AgilidadFisicaSuperHumano;
    private javax.swing.JFormattedTextField AgilidadMetalSuperHumano;
    private javax.swing.JButton AgregarEscuadrones;
    private javax.swing.JButton AgregarMiembroSuperheroe;
    private javax.swing.JButton AgregarMiembroVillano;
    private javax.swing.JButton AgregarSuperHumano;
    private javax.swing.JTextField DebilidadSuperHumano;
    private javax.swing.JMenuItem EliminarEscuadronSuperHeroes;
    private javax.swing.JMenuItem EliminarSuperheroe;
    private javax.swing.JMenuItem EliminarVillano;
    private javax.swing.JFormattedTextField FuerzaSuperHumano;
    private javax.swing.JTree JtreeEscuadrones;
    private javax.swing.JList<String> ListaEscuadrones;
    private javax.swing.JList<String> ListaSuperHeroes;
    private javax.swing.JList<String> ListaVillanos;
    private javax.swing.JComboBox<String> MiembrosSuperheroes;
    private javax.swing.JComboBox<String> MiembrosVillanos;
    private javax.swing.JMenuItem ModificarEscuadronSuperheroes;
    private javax.swing.JMenuItem ModificarSuperheroe;
    private javax.swing.JMenuItem ModificarVillano;
    private javax.swing.JTextField NombreSuperHumano;
    private javax.swing.JTextField PoderSuperHumano;
    private javax.swing.JPopupMenu PopUpEscuadron;
    private javax.swing.JPopupMenu PopUpSuperheroes;
    private javax.swing.JPopupMenu PopUpVillanos;
    private javax.swing.JRadioButton SuperHeroeRadio;
    private javax.swing.JFrame VentanaEscuadronSuperheroes;
    private javax.swing.JFrame VentanaEscuadronVillanos;
    private javax.swing.JRadioButton VillanoRadio;
    private javax.swing.JTextField baseescuadron;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nombreescuadron;
    private javax.swing.JRadioButton superheroeradioescua;
    private javax.swing.JRadioButton villanoradioescua;
    // End of variables declaration//GEN-END:variables
private ArrayList<String> nombres = new ArrayList();
    private ArrayList<Villano> miembrosvillanos = new ArrayList();
    private ArrayList<Superheroe> miembrosheroes = new ArrayList();
}
